# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artcile',
            new_name='Article',
        ),
    ]
